// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: pkg/proto/users/users.proto

package users

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_pkg_proto_users_users_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_users_users_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_pkg_proto_users_users_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

type CreateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DisplayName   string                 `protobuf:"bytes,1,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_pkg_proto_users_users_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_users_users_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_users_users_proto_rawDescGZIP(), []int{1}
}

func (x *CreateUserRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

type GetUserByNameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DisplayName   string                 `protobuf:"bytes,1,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByNameRequest) Reset() {
	*x = GetUserByNameRequest{}
	mi := &file_pkg_proto_users_users_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByNameRequest) ProtoMessage() {}

func (x *GetUserByNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_users_users_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByNameRequest.ProtoReflect.Descriptor instead.
func (*GetUserByNameRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_users_users_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserByNameRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

var File_pkg_proto_users_users_proto protoreflect.FileDescriptor

const file_pkg_proto_users_users_proto_rawDesc = "" +
	"\n" +
	"\x1bpkg/proto/users/users.proto\x12\x05users\"9\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\"6\n" +
	"\x11CreateUserRequest\x12!\n" +
	"\fdisplay_name\x18\x01 \x01(\tR\vdisplayName\"9\n" +
	"\x14GetUserByNameRequest\x12!\n" +
	"\fdisplay_name\x18\x01 \x01(\tR\vdisplayName2{\n" +
	"\x05Users\x125\n" +
	"\n" +
	"CreateUser\x12\x18.users.CreateUserRequest\x1a\v.users.User\"\x00\x12;\n" +
	"\rGetUserByName\x12\x1b.users.GetUserByNameRequest\x1a\v.users.User\"\x00B1Z/github.com/neelalala/go-storage/pkg/proto/usersb\x06proto3"

var (
	file_pkg_proto_users_users_proto_rawDescOnce sync.Once
	file_pkg_proto_users_users_proto_rawDescData []byte
)

func file_pkg_proto_users_users_proto_rawDescGZIP() []byte {
	file_pkg_proto_users_users_proto_rawDescOnce.Do(func() {
		file_pkg_proto_users_users_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_users_users_proto_rawDesc), len(file_pkg_proto_users_users_proto_rawDesc)))
	})
	return file_pkg_proto_users_users_proto_rawDescData
}

var file_pkg_proto_users_users_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pkg_proto_users_users_proto_goTypes = []any{
	(*User)(nil),                 // 0: users.User
	(*CreateUserRequest)(nil),    // 1: users.CreateUserRequest
	(*GetUserByNameRequest)(nil), // 2: users.GetUserByNameRequest
}
var file_pkg_proto_users_users_proto_depIdxs = []int32{
	1, // 0: users.Users.CreateUser:input_type -> users.CreateUserRequest
	2, // 1: users.Users.GetUserByName:input_type -> users.GetUserByNameRequest
	0, // 2: users.Users.CreateUser:output_type -> users.User
	0, // 3: users.Users.GetUserByName:output_type -> users.User
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_proto_users_users_proto_init() }
func file_pkg_proto_users_users_proto_init() {
	if File_pkg_proto_users_users_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_users_users_proto_rawDesc), len(file_pkg_proto_users_users_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_users_users_proto_goTypes,
		DependencyIndexes: file_pkg_proto_users_users_proto_depIdxs,
		MessageInfos:      file_pkg_proto_users_users_proto_msgTypes,
	}.Build()
	File_pkg_proto_users_users_proto = out.File
	file_pkg_proto_users_users_proto_goTypes = nil
	file_pkg_proto_users_users_proto_depIdxs = nil
}
