services:
  gateway:
    build:
      context: .
      dockerfile: cmd/gateway/Dockerfile
    restart: unless-stopped
    depends_on:
      metadata:
        condition: service_started
      storage-1:
        condition: service_started
      storage-2:
        condition: service_started
      storage-3:
        condition: service_started
    ports:
      - "8080:80"
    environment:
      - NO_PROXY=postgres,localhost,127.0.0.1

  metadata:
    build:
      context: .
      dockerfile: cmd/metadata/Dockerfile
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env

  users:
    build:
      context: .
      dockerfile: cmd/users/Dockerfile
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env

  storage-1:
    build:
      context: .
      dockerfile: cmd/storage/Dockerfile
    volumes:
      - ./uploads/node1:/uploads/ver1
    restart: unless-stopped
    environment:
      - NODE_NAME=node1
      - NO_PROXY=postgres,localhost,127.0.0.1

  storage-2:
    build:
      context: .
      dockerfile: cmd/storage/Dockerfile
    volumes:
      - ./uploads/node2:/uploads/ver1
    restart: unless-stopped
    environment:
      - NODE_NAME=node2
      - NO_PROXY=postgres,localhost,127.0.0.1

  storage-3:
    build:
      context: .
      dockerfile: cmd/storage/Dockerfile
    volumes:
      - ./uploads/node3:/uploads/ver1
    restart: unless-stopped
    environment:
      - NODE_NAME=node3
      - NO_PROXY=postgres,localhost,127.0.0.1

  postgres:
    image: postgres:17-alpine
    env_file:
      - .env
    ports:
      - "5430:5432"
    volumes:
      - ./pgdata:${PGDATA}
    restart: unless-stopped
    tty: true
    stdin_open: true
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 3s
      timeout: 3s
      retries: 5
    environment:
      - NO_PROXY=postgres,localhost,127.0.0.1

networks:
  go-storage-network:
    driver: bridge
