services:
  gateway:
    build:
      context: .
      dockerfile: cmd/gateway/Dockerfile
    restart: unless-stopped
    depends_on:
      metadata:
        condition: service_started
      storage:
        condition: service_started
    ports:
      - "8080:80"
    environment:
      - NO_PROXY=postgres,localhost,127.0.0.1

  metadata:
    build:
      context: .
      dockerfile: cmd/metadata/Dockerfile
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env

  storage:
    build:
      context: .
      dockerfile: cmd/storage/Dockerfile
    volumes:
      - ./uploads:/uploads/ver1
    restart: unless-stopped
    environment:
      - NO_PROXY=postgres,localhost,127.0.0.1

  postgres:
    image: postgres:17-alpine
    env_file:
      - .env
    ports:
      - "5430:5432"
    volumes:
      - ./pgdata:${PGDATA}
    restart: unless-stopped
    tty: true
    stdin_open: true
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 3s
      timeout: 3s
      retries: 5
    environment:
      - NO_PROXY=postgres,localhost,127.0.0.1

networks:
  go-storage-network:
    driver: bridge