services:
  gateway:
    build:
      context: .
      dockerfile: cmd/gateway/Dockerfile
    restart: unless-stopped
    depends_on:
      metadata:
        condition: service_started
    ports:
      - "8080:80"
    environment:
      - NO_PROXY=postgres,localhost,127.0.0.1

  metadata:
    build:
      context: .
      dockerfile: cmd/metadata/Dockerfile
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env

  users:
    build:
      context: .
      dockerfile: cmd/users/Dockerfile
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env

  storage-1:
    build:
      context: .
      dockerfile: cmd/storage/Dockerfile
    volumes:
      - ./uploads/node1:/uploads/ver1
    restart: unless-stopped
    environment:
      - NODE_ID=78463b59-79ee-44c6-b610-18b4549d60f6
      - SERVER_ADDRESS_GRPC=storage-1:50051
      - NO_PROXY=postgres,localhost,127.0.0.1

  storage-2:
    build:
      context: .
      dockerfile: cmd/storage/Dockerfile
    volumes:
      - ./uploads/node2:/uploads/ver1
    restart: unless-stopped
    environment:
      - NODE_ID=203faea7-1211-4234-8733-05cc840e348f
      - SERVER_ADDRESS_GRPC=storage-2:50051
      - NO_PROXY=postgres,localhost,127.0.0.1

  storage-3:
    build:
      context: .
      dockerfile: cmd/storage/Dockerfile
    volumes:
      - ./uploads/node3:/uploads/ver1
    restart: unless-stopped
    environment:
      - NODE_ID=111ebee6-29c7-46fe-ac62-85489820eec9
      - SERVER_ADDRESS_GRPC=storage-3:50051
      - NO_PROXY=postgres,localhost,127.0.0.1

  postgres:
    image: postgres:17-alpine
    env_file:
      - .env
    ports:
      - "5430:5432"
    volumes:
      - ./pgdata:${PGDATA}
    restart: unless-stopped
    tty: true
    stdin_open: true
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 3s
      timeout: 3s
      retries: 5
    environment:
      - NO_PROXY=postgres,localhost,127.0.0.1

networks:
  go-storage-network:
    driver: bridge
